module RequestAction
  # To change this template use File | Settings | File Templates.
  CREATE='CREATE'
  APPLY='APPLY'
  ACCEPT='ACCEPT'
  REJECT='REJECT'
  UPLOAD='UPLOAD'
  SUBMIT_PROCESS='SUBMIT_PROCESS'
  CANCEL='CANCEL'
  DROPOUT='DROPOUT'
  PAY='PAY'
  HAND_IN='HAND_IN'
  MARK_AS_ACCEPTED='MARK_AS_ACCEPTED'
  FINISHED='FINISHED'
end